name: managePlayers
description: $description
version: '1.4'

main: cd.misakplak.managePlayers
paperPluginLoader: cd.misakplak.managePlayersLoader
api-version: '1.21.11'
load: POSTWORLD

authors: [ misakplak ]


commands:

  manage:
    usage: /manage {player}
    description: a gui to manage players
    permission: manage
    permission-message: "§cYou cannot use this cmd"


permissions:
  manage.*:
    description: Gives access to all ManagePlayers permissions
    default: op
    children:
      manage.command: true
      manage.tp: true
      manage.tphere: true
      manage.kick: true
      manage.ban: true
      manage.seeinv: true

  manage.command:
    description: Allows using /manage
    default: false

  manage.tp:
    description: Allows teleporting to players
    default: false

  manage.tphere:
    description: Allows teleporting players to you
    default: false

  manage.kick:
    description: Allows kicking players
    default: false

  manage.ban:
    description: Allows banning players
    default: false

  manage.seeinv:
    description: Allows viewing player inventories
    default: false

