name: managePlayers
description: $description
version: '1.0-SNAPSHOT'

main: cd.misakplak.managePlayers
paperPluginLoader: cd.misakplak.managePlayersLoader
api-version: '26.1.2'
load: POSTWORLD

authors: [ misakplak ]


commands:

  manage:
    usage: /manage {player}
    description: a gui to manage players
    permission: manage
    permission-message: "§cYou cannot use this cmd"


permissions:

  manage:
    description: a perm for manage command
    default: op

  manage.tphere:
    description: "allow using teleport here in manage GUI"
    default: op

  manage.tp:
    description: "allow using teleport in manage GUI"
    default: op


  manage.kick:
    description: "allow using kick in manage GUI"
    default: op

  manage.ban:
    default: op
    description: "allow using ban in manage GUI"

